### ISSUE TITLE
it returns false when validate wildcard cert with domain.

### ISSUE THREAD

**Issue by dogenius01** [Losant/ssl-validator#4] opened 2019-10-22 07:35 UTC
Cert is for *.test.com
and domain is a.test.com.

let cert = `~~~`;
let domain = 'a.test.com';

let result = await sslValidator.isValidSSL(cert, {domain: domain, skipDateValidation: false});

result is false.

**Comment by dogenius01** [comment] 2019-10-22 08:06
3 depth domain must have more than 2 character.

**Comment by dogenius01** [comment] 2019-10-25 00:06
how about "m.xxx.com" ??
It should work, right?

**Comment by dogenius01** [comment] 2019-10-25 02:32
Also, "test.test.xxx.com" always return false.

**Comment by spacetc62** [comment] 2020-02-26 01:51
Thanks for the issue report (and sorry about our delay in fixing it - somehow missed the notifications). The issue is fixed in [v1.0.6](https://github.com/Losant/ssl-validator/blob/master/CHANGELOG.md#106---2020-02-25)

**Closed by spacetc62** 2020-02-26 01:51 UTC
